import 'dart:io';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/debt_model.dart';

class PdfService {
  static Future<File> generateDebtReport(List<DebtModel> debts) async {
    final pdf = pw.Document();

    final currency = NumberFormat("#,##0", "id_ID");
    final now = DateTime.now();

    final totalDebt = debts.fold(0.0, (sum, item) => sum + item.totalAmount);

    final totalPaid = debts.fold(0.0, (sum, item) => sum + item.totalPaid);

    final totalRemaining = debts.fold(0.0, (sum, item) => sum + item.remaining);

    pdf.addPage(
      pw.MultiPage(
        margin: const pw.EdgeInsets.all(24),

        build: (context) => [
          // HEADER
          pw.Text(
            "Debt Manager Report",
            style: pw.TextStyle(fontSize: 26, fontWeight: pw.FontWeight.bold),
          ),

          pw.SizedBox(height: 4),

          pw.Text(
            "Laporan Hutang Pengguna",
            style: const pw.TextStyle(fontSize: 14),
          ),

          pw.SizedBox(height: 10),

          pw.Text(
            "Tanggal Cetak: ${DateFormat('dd MMM yyyy HH:mm').format(now)}",
          ),

          pw.Divider(),

          pw.SizedBox(height: 10),

          // SUMMARY
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(border: pw.Border.all()),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  "Ringkasan",
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 8),
                pw.Text("Total Hutang : Rp ${currency.format(totalDebt)}"),
                pw.Text("Sudah Dibayar : Rp ${currency.format(totalPaid)}"),
                pw.Text("Sisa Hutang : Rp ${currency.format(totalRemaining)}"),
              ],
            ),
          ),

          pw.SizedBox(height: 20),

          // TABLE
          pw.Text(
            "Detail Data",
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
          ),

          pw.SizedBox(height: 10),

          pw.Table.fromTextArray(
            border: pw.TableBorder.all(),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            headerHeight: 30,
            cellHeight: 28,
            cellAlignments: {
              0: pw.Alignment.centerLeft,
              1: pw.Alignment.centerRight,
              2: pw.Alignment.centerRight,
              3: pw.Alignment.centerRight,
              4: pw.Alignment.center,
            },
            headers: ["Nama", "Total", "Bayar", "Sisa", "Status"],
            data: debts.map((debt) {
              return [
                debt.title,
                currency.format(debt.totalAmount),
                currency.format(debt.totalPaid),
                currency.format(debt.remaining),
                debt.remaining <= 0 ? "Lunas" : "Aktif",
              ];
            }).toList(),
          ),
        ],

        footer: (context) {
          return pw.Center(
            child: pw.Text(
              "Generated by Debt Manager",
              style: const pw.TextStyle(fontSize: 10),
            ),
          );
        },
      ),
    );

    final dir = await getApplicationDocumentsDirectory();

    final file = File("${dir.path}/laporan_hutang.pdf");

    await file.writeAsBytes(await pdf.save());

    return file;
  }
}
